### ISSUE TITLE
Things to do for Registration:

### ISSUE THREAD

**Issue by alexjaffray** [NordicMRspine/MRINavigator.jl#26]
1. Rename package to MRINavigator.jl
2. Add [compat] entries with upper bounds

**Comment by alexjaffray** [comment]
@Laura2305 I'm on the plane to Europe, can you do these things? Once they are done, I will use the registrator and we should be good.

**Comment by Laura2305** [comment]
@alexjaffray sure!

1. Done
2. I'm opening PRs for the CompactHelper branches and merging them in the main branch. Is this what you mean?

**Comment by alexjaffray** [comment]
At the moment, the list of compat entries that need adding is the following:

CSV
DataFrames
Documenter
ImageUtils
Images
NIfTI

Once we do that we should be good to register

**Comment by alexjaffray** [comment]
@Laura2305 Closing this, as it has been registered. Try `add MRINavigator` anywhere in Julia and it should add our package.
