### ISSUE TITLE
Slices and echoes selection

### ISSUE THREAD

**Issue by Laura2305** [NordicMRspine/MRINavigator.jl#46]
To be fixed in the package and user examples:
- Echos selection --> error when running some of the AdjustData.jl functions with echo = nothing
- Slices selection problem --> error in the user example and main.jl file when selecting slices
- Slices selection problem --> error in the unwrap function when only two slices are selected

**Comment by alexjaffray** [comment]
@Laura2305 let me know when the other PRs (#48 and #49) are ready for review

**Comment by Laura2305** [comment]
@alexjaffray PRs #48 and #49 are ready for review.

**Comment by Laura2305** [comment]
@alexjaffray It would be great if you could review these PRs and the PR in the User_Example folder before ISMRM, as someone may want to download the package after the conference.

**Comment by alexjaffray** [comment]
@Laura2305 I'll review today

**Comment by alexjaffray** [comment]
@Laura2305 Finalized my review, only a few things need addressing before approval

**Comment by Laura2305** [comment]
@alexjaffray Thanks! I've completed the changes you requested. We should consider making a new release, as the current released version is quite outdated and contains multiple bugs that have been resolved.

**Comment by alexjaffray** [comment]
@Laura2305 I've approved, feel free to merge

**Comment by Laura2305** [comment]
@alexjaffray thanks! I've merged and made a new release.
